org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

curseforgeId=1056828
modrinthId=2oORTOi2

# Forestry
forestryVersion=3.0.0-alpha1

# Minecraft
minecraftVersion=1.21.1
mappingsVersion=2024.11.17
# NeoForge
forgeVersion=21.1.230
forgeVersionRange=[21.1,)
fmlVersionRange=[4,)
# JEI
jeiVersion=19.27.0.340
jeiVersionRange=[19,)
# Patchouli
patchouliVersion=1.21.1-93
patchouliVersionRange=[1.21.1-92,)
# KubeJS
kubejsVersion=2101.7.2-build.368
rhinoVersion=2101.2.7-build.81
architecturyVersion=13.0.8
# Curios
curiosVersion=9.5.1
# Ponder https://ci.createmod.net/job/createmod/job/Ponder/
ponderVersion=1.0.87
