package forestry.core.data;

import forestry.api.ForestryConstants;
import forestry.api.IForestryApi;
import forestry.apiimpl.plugin.PluginManager;
import forestry.core.data.models.ForestryBlockStateProvider;
import forestry.core.data.models.ForestryItemModelProvider;
import forestry.core.data.models.ForestryWoodModelProvider;
import forestry.core.data.recipe.ForestryRecipeProvider;
import forestry.modules.ForestryModuleManager;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.data.event.GatherDataEvent;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import thedarkcolour.modkit.data.DataHelper;

import java.util.concurrent.CompletableFuture;

@EventBusSubscriber(modid = ForestryConstants.MOD_ID)
public class Data {
	@SubscribeEvent
	public static void gatherData(GatherDataEvent event) {
		preDataGen();

		DataGenerator generator = event.getGenerator();
		PackOutput output = generator.getPackOutput();
		ExistingFileHelper existingFileHelper = event.getExistingFileHelper();
		DataHelper dataHelper = new DataHelper(ForestryConstants.MOD_ID, event);
		CompletableFuture<HolderLookup.Provider> lookup = event.getLookupProvider();

		dataHelper.createEnglish(true, ForestryEnglishProvider::addTranslations);
		dataHelper.createTags(Registries.BLOCK, ForestryBlockTagsProvider::addTags);
		dataHelper.createTags(Registries.ITEM, (tags, l) -> {
			ForestryItemTagsProvider.addTags(tags);
			ForestryBackpackTagProvider.addTags(tags);
		});
		dataHelper.createTags(Registries.BIOME, ForestryBiomeTagsProvider::addTags);
		dataHelper.createTags(Registries.FLUID, ForestryFluidTagsProvider::addTags);
		dataHelper.createTags(Registries.POINT_OF_INTEREST_TYPE, ForestryPoiTypeTagProvider::addTags);
		// painting_variant became a datapack registry in 1.21; the painting JSONs and
		// the placeable tag are shipped under src/main/resources/data/forestry/painting_variant/
		// and data/minecraft/tags/painting_variant/placeable.json respectively. A small
		// validator (below) fails datagen if a variant JSON is missing from the tag.
		generator.addProvider(event.includeServer(), new ForestryPaintingPlaceableValidator());
		dataHelper.createRecipes(ForestryRecipeProvider::addRecipes);
		dataHelper.createDamageTypes(ForestryDamageTypesProvider::addTypes);
		dataHelper.createItemModels(false, false, false, ForestryItemModels::addModels);

		generator.addProvider(event.includeServer(), new ForestryAdvancementProvider(output, lookup, existingFileHelper));
		generator.addProvider(event.includeServer(), new ForestryLootTableProvider(output, lookup));
		generator.addProvider(event.includeServer(), new ForestryLootModifierProvider(output, lookup));
		generator.addProvider(event.includeClient(), new ForestryBlockStateProvider(output, existingFileHelper));
		generator.addProvider(event.includeClient(), new ForestryWoodModelProvider(output, existingFileHelper));
		generator.addProvider(event.includeClient(), new ForestryItemModelProvider(output, existingFileHelper));
		generator.addProvider(event.includeClient(), new ForestryAtlasProvider(output, lookup, existingFileHelper));
		generator.addProvider(event.includeServer(), new ForestryFeaturesProvider(output, lookup));
		generator.addProvider(event.includeServer(), new TaxonProvider(output));
		generator.addProvider(event.includeServer(), new FlowerTypeProvider(output));
		generator.addProvider(event.includeServer(), new BeeEffectProvider(output, lookup));
		generator.addProvider(event.includeServer(), new BeeSpeciesProvider(output, lookup));
		generator.addProvider(event.includeServer(), new TreeSpeciesProvider(output, lookup));
		generator.addProvider(event.includeServer(), new ButterflySpeciesProvider(output, lookup));
		generator.addProvider(event.includeServer(), new MutationProvider(output, lookup));
		generator.addProvider(event.includeServer(), new ForestryDataMapProvider(output, lookup));
		generator.addProvider(event.includeClient(), new ForestryCuriosProvider(output, existingFileHelper, lookup));
	}

	// Hack fix to make API work in data generation environment
	public static void preDataGen() {
		((ForestryModuleManager) IForestryApi.INSTANCE.getModuleManager()).setupApi();

		PluginManager.registerClient();

		// Base Forestry's taxonomy now ships as datapack JSON (generated by TaxonProvider), loaded at real server start
		// via a reload listener - but a standalone data generator run never fires that reload cycle. A species' genus
		// must resolve to a taxon when the species is seeded below, so seed the live taxonomy from the same source
		// TaxonProvider generates its JSON from, before anything touches species.
		TaxonProvider.seedLiveTaxaForDatagen();

		// Flower types now come exclusively from the datapack JSON generated by FlowerTypeProvider, loaded at real
		// server start via a reload listener - but a standalone data generator run never fires that reload cycle.
		// Karyotype default-allele resolution for the FLOWER_TYPE chromosome (bee/butterfly species genome building,
		// below) requires the built-ins to already be registered, so seed them from the same source
		// FlowerTypeProvider generates its JSON from before anything touches species.
		FlowerTypeProvider.seedLiveFlowerTypesForDatagen();

		// Some built-in bee effects are likewise datapack-defined (generated by BeeEffectProvider) rather than
		// code-registered; the bee_effect chromosome default-allele resolution below needs them merged onto the
		// code-registered effects (already set by setupApi() above) before any bee species is built.
		BeeEffectProvider.seedLiveBeeEffectsForDatagen();

		// Bee species now come exclusively from the datapack JSON generated by BeeSpeciesProvider, loaded at real
		// server start via a reload listener - but a standalone data generator run never fires that reload cycle.
		// Loot tables reference bees by id (LootTableHelper#beeLoot -> OrganismFunction.fromId), so they need no live
		// species. The one remaining consumer is the centrifuge recipe whose *result* is a concrete bee ItemStack
		// (ForestryRecipeProvider -> BEE_TYPE.createStack(RELIC, DRONE)): a bee stack's identity is its full genome
		// component, so building the result materializes a live species. Until that recipe result also references the
		// bee by id (see the lazy id-template-stack follow-up), seed the live species type from the same
		// DefaultBeeSpecies source BeeSpeciesProvider generates its JSON from.
		BeeSpeciesProvider.seedLiveSpeciesForDatagen();

		// Tree species come from datapack JSON at real server start; datagen never fires that reload, so seed the
		// live tree type from the same DefaultTreeSpecies source any stack-baking provider/loot needs.
		TreeSpeciesProvider.seedLiveSpeciesForDatagen();

		// Butterfly species come from datapack JSON at real server start; datagen never fires that reload, so seed
		// the live butterfly type from the same DefaultButterflySpecies source any stack-baking provider/loot needs.
		ButterflySpeciesProvider.seedLiveSpeciesForDatagen();
	}
}
