modLoader = "javafml"
loaderVersion = "{fmlVersionRange}"
issueTrackerURL = "https://github.com/thedarkcolour/ForestryCE/issues"

license = "GNU Lesser Public License v3"

[[mods]]
modId = "forestry"
version = "${version}"
displayName = "Forestry"
displayURL = "https://github.com/thedarkcolour/ForestryCE"
logoFile = "forestry_logo.png"
credits = "mistaqur, Binnie, CovertJaguar, MysteriousAges, Nirek, Temp1011, ramidzkh, EnderiumSmith, Spearkiller"
authors = "SirSengir, mezz, Nedelosk, thedarkcolour"
description = '''
	Trees, bees and more.
	'''

[[dependencies.forestry]]
modId = "neoforge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.forestry]]
modId = "patchouli"
type = "REQUIRED"
versionRange = "${patchouliVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.forestry]]
modId = "jei"
type = "OPTIONAL"
versionRange = "${jeiVersionRange}"
ordering = "NONE"
side = "CLIENT"
